# Generated by Django 5.0.2 on 2025-01-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gm',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
    ]
